In [5]:
import numpy as np
data = np.random.randn(2,3)
data

array([[-0.86413616,  0.7336551 , -1.04556831],
       [ 0.54498122, -1.40231124, -0.50902407]])

In [6]:
data*10

array([[ -8.64136159,   7.33655099, -10.45568307],
       [  5.44981223, -14.02311242,  -5.09024071]])

In [7]:
data + data

array([[-1.72827232,  1.4673102 , -2.09113661],
       [ 1.08996245, -2.80462248, -1.01804814]])

In [9]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
arr1.shape

(5,)

In [19]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.shape
arr2.ndim

2

In [24]:
arr2.dtype

dtype('int64')

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
zero_3 = np.zeros((3,6))
zero_3.ndim
zero_3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
np.empty((1,3,2)) #first parameter in tuple is superior parameter dimension

array([[[0.86413616, 0.7336551 ],
        [1.04556831, 0.54498122],
        [1.40231124, 0.50902407]]])

In [39]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
arr = np.random.randn(2,3)
np.zeros_like(arr)
np.ones_like(arr)
np.empty_like(arr)
arr

array([[-1.26723277, -0.86140047,  2.11659035],
       [ 0.22939576, -0.19576211,  1.81361181]])

In [47]:
lis = [[1,2,3], [4,5,6]]
list_arr = np.asarray(lis)
list_arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [58]:
#Produce an array of the given shape and dtype with all values set to the indicated "full value"
np.full((2,3),1)
np.full_like(arr, 2)

array([[2., 2., 2.],
       [2., 2., 2.]])

In [60]:
np.eye(2)
np.identity(2,float)

array([[1., 0.],
       [0., 1.]])

#Data Types for ndarrays

In [69]:
arr1 = np.array([1,2,3], dtype = np.float16)
arr2 = np.array([1,2,3], dtype = np.int8)
print(arr1, '\n', arr2)

[1. 2. 3.] 
 [1 2 3]


In [62]:
arr1.dtype

dtype('float64')

In [74]:
arr = np.array([1,2,3,4,5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [77]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
int_arr = arr.astype('int64')
int_arr

array([ 3, -1, -2,  0, 12, 10])

In [104]:
#numeric_Strings
numeric_string = np.array(['1,24', '-9.6', '42.0'], dtype=np.string_)
numeric_string.astype(np.float64)

ValueError: could not convert string to float: b'1,24'

In [100]:
np.float

/var/folders/l9/glqlxsms6kg26pc8n2s189hw0000gn/T/ipykernel_1518/699376334.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float


float

In [105]:
int_array = np.arange(10)
calibers= np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [109]:
empty_unit32 = np.empty(8,dtype = 'u4')
empty_unit32

array([         0, 1072693248,          0,          0,          0,
                0,          0, 1072693248], dtype=uint32)

In [7]:
import numpy as np
np.zeros((2,2), dtype = np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)